apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hyperdx-s3-credentials
    namespace: hyperdx
spec:
    secretTemplates:
        - name: hyperdx-s3-credentials
          type: Opaque
          stringData:
            HYPERDX_S3_ACCESS_KEY: ENC[AES256_GCM,data:Ymzf0iuGQExzAbYcOlqLzFv1K4eVJBrckrg=,iv:e8J9FzZGmVwv1GHcnozrEw8QWKySxuchgFFH/ATB1/U=,tag:evalFTeHBv+k22Zkr5Y7qg==,type:str]
            HYPERDX_S3_SECRET_KEY: ENC[AES256_GCM,data:Zm3osdKJ1za1t3QabdP7cYmPSCsxqb5EnFJeDdbV2fwpQPLJtFHAOPL8oEb39/GtpBuG9rQPgeCJg7rbErKVIw==,iv:DaLSR6lLd0vw0TP3DdjQomwqtHtInwfjIqxIBQrqInQ=,tag:ezq6AM5PNp/o0kEC2gpWXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dzBDTitBamRqT2dPdVAz
            aXpHdGdxN3VNM2VQdDI0VFFVSEpqLzV2aDM0CktJTmUzTFBKUzNUN2x1cEkvYjJ1
            U3FublB6Mk9QMGI0SW56emU4aXBRNGsKLS0tIHZFbGZTbWo1Tk1vV2hiSC8zNkJX
            VUVVMWE2T2tYcXRLeTlyT05iazdCY0kKqxtOHZ5tv6J2JL/u/gttkB0SWRIy1wSQ
            CJuUASUFSRMteb2Ngj6XuYNt0RQ5hYU/8/jny30vWNo6kUgX+oUFcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tf6hky66y70lgkd9petf5tzempxltsh2kpe0nqs696ascnyyk5eqfvyyuh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVllEdHN5T0hKaytXcWRL
            OHRqOHBoY0lZbGgwNVQ1UkNuUm5KQjRGdG1FCmU1cUdlRVh5NzdCSTVyeFhBOXNI
            aTlnWWd6bG9rQjZ0SzFwU2xaQ2gva1kKLS0tIHM5ZHB0Z2Mvd2hDT3l0VVRPN1hW
            MGgrcnVvUFR0MG5KUWs2QnFoMXQzUlkKdOkL/tpILigNyT8k5AL0QccPZg2KPK7g
            x7HzNB2WO2ilWgboLH3tq9HkIxWq/r4M1gg2dqab5tv3qvwU5UwhGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T18:10:52Z"
    mac: ENC[AES256_GCM,data:Rax5njwqncftOhnFh1xzLnh8mYkrkurOJN0kLCZqc75WFGCo8FJwoJU965NDkFO2A2/kMCSmQW1fgawQ8WnNB98GV59803MHR7J1MpUggkYNM+B82vMT1ZoqbMCE9NxmAx6+6hxynWtriLankLzhpN+FaaeiMf3PJXsc/atJWic=,iv:gsrepaOpJOzMVcucsLeumTIK4PogH53Utfe7lpq1EYk=,tag:duaQ5sm5rq3wkqWKTIfLvQ==,type:str]
    version: 3.13.0
